<?php
/**
 * Project: 
 * Contenido Content Management System
 * 
 * Description: 
 * Defines all general variables of Contenido.
 * 
 * NOTE: This configuration file was generated by Contenido setup!
 * 
 * Requirements: 
 * @con_php_req 5.0
 * 
 *
 * @package    Contenido Backend classes
 * @version    1.1.2
 * @author     unknown
 * @copyright  four for business AG <www.4fb.de>
 * @license    http://www.contenido.org/license/LIZENZ.txt
 * @link       http://www.4fb.de
 * @link       http://www.contenido.org
 * 
 * {@internal 
 *   created  2010-05-16
 *   modified 2010-05-20, Murat Purc, removed request check during processing ticket [#CON-307]
 *   modified 2011-08-24, Dominik Ziegler, changed default server path and web url definitions [#CON-430]

 *   
 *   $Id$
 * }}
 * 
 */


defined('CON_FRAMEWORK') or die('Illegal call');


global $cfg;

/* Section 1: Path settings
 * ------------------------
 *
 * Path settings which will vary along different
 * Contenido settings.
 *
 * A little note about web and server path settings:
 * - A Web Path can be imagined as web addresses. Example:
 *   http://192.168.1.1/test/
 * - A Server Path is the path on the server's hard disk. Example:
 *   /var/www/html/contenido    for Unix systems OR
 *   c:/htdocs/contenido        for Windows systems
 *
 * Note: If you want to modify the locations of subdirectories for
 *       some reason (e.g. the includes directory), see Section 8.
 */
 
/* The root server path where all frontends reside */
$cfg['path']['frontend']                = '{CONTENIDO_ROOT}'; 

/* The root server path to the contenido backend */
$cfg['path']['contenido']               = $cfg['path']['frontend'] . '/contenido/';

/* The root server path to the conlib directory */
$cfg['path']['phplib']                  = $cfg['path']['frontend'] . '/conlib/';

/* The root server path to the pear directory */
$cfg['path']['pear']                    = $cfg['path']['frontend'] . '/pear/';

/* The server path to all WYSIWYG-Editors */
$cfg['path']['all_wysiwyg']             = $cfg['path']['contenido']  . 'external/wysiwyg/';

/* The server path to the desired WYSIWYG-Editor */
$cfg['path']['wysiwyg']                 = $cfg['path']['all_wysiwyg'] . 'tinymce3/';

/* The web server path to the contenido backend */
$cfg['path']['contenido_fullhtml']      = '{CONTENIDO_WEB}/contenido/';

/* The web path to all WYSIWYG-Editors */
$cfg['path']['all_wysiwyg_html']        = $cfg['path']['contenido_fullhtml'] . 'external/wysiwyg/';

/* The web path to the desired WYSIWYG-Editor */
$cfg['path']['wysiwyg_html']            = $cfg['path']['all_wysiwyg_html'] . 'tinymce3/';



/* Section 2: Database settings
 * ----------------------------
 *
 * Database settings for MySQL. Note that we don't support
 * other databases in this release.
 */

/* The prefix for all contenido system tables, usually "con" */
$cfg['sql']['sqlprefix'] = '{MYSQL_PREFIX}';

/* The host where your database runs on */
$contenido_host = '{MYSQL_HOST}';

/* The database name which you use */
$contenido_database = '{MYSQL_DB}';

/* The username to access the database */
$contenido_user = '{MYSQL_USER}';

/* The password to access the database */
$contenido_password = '{MYSQL_PASS}';

$cfg["database_extension"] = '{DB_EXTENSION}';

$cfg["nolock"] = '{NOLOCK}';

$cfg["is_start_compatible"] = {START_COMPATIBLE};

?>