<?php
/*****************************************
* File      :   $RCSfile: include.recipients.group.subnav.php,v $
* Project   :   Contenido
* Descr     :   Custom subnavigation for the newsletter recipient groups
* Modified  :   $Date: 2007/06/19 23:18:38 $
*
* © four for business AG, www.4fb.de, generated by HerrB (01.08.2004)
*
* $Id: include.recipients.group.subnav.php,v 1.6 2007/06/19 23:18:38 bjoern.behrens Exp $
******************************************/
if ( $_REQUEST['cfg'] ) { exit; }

if (isset($_GET['idrecipientgroup']) && (int)$_GET['idrecipientgroup'] > 0)
{
	$caption = i18n("Overview");
	$tmp_area = "foo2";

	# Set template data
	$tpl->set("d", "ID",        'c_'.$tpl->dyn_cnt);
	$tpl->set("d", "CLASS",     '');
	$tpl->set("d", "OPTIONS",   '');
	$tpl->set("d", "CAPTION",   '<a class="white" onclick="sub.clicked(this)" target="right_bottom" href="'.$sess->url("main.php?area=$area&frame=4&idrecipientgroup=$idrecipientgroup").'">'.$caption.'</a>');
	$tpl->next();
    
	if (is_array($cfg['plugins']['recipientslogic'])) {
		foreach ($cfg['plugins']['recipientslogic'] as $plugin) {
			cInclude("plugins", "recipientslogic/$plugin/".$plugin.".php");

			$className = "recipientslogic_".$plugin;    
			$class     = new $className;
    
			$caption   = $class->getFriendlyName();
			$tmp_area  = "foo2";    	
			$tpl->set("d", "ID",        'c_'.$tpl->dyn_cnt);
			$tpl->set("d", "CLASS",     '');
			$tpl->set("d", "OPTIONS",   '');
			$tpl->set("d", "CAPTION",   '<a class="white" onclick="sub.clicked(this)" target="right_bottom" href="'.$sess->url("main.php?area=recipientgroup_rights&frame=4&useplugin=$plugin&idrecipientgroup=$idrecipientgroup").'">'.$caption.'</a>');
			$tpl->next();
		}
	}

	$tpl->set('s', 'COLSPAN', ($tpl->dyn_cnt * 2) + 2);

	# Generate the third navigation layer
	$tpl->generate($cfg["path"]["templates"] . $cfg["templates"]["subnav"]);
} else {
	include ($cfg["path"]["contenido"].$cfg["path"]["templates"] . $cfg["templates"]["right_top_blank"]);
}

?>